ardupilot_manager: Detector: use IntEnum instead of Enum
Fixes a new mypy issue caused by the comparison of objects which
Do not implement the "less than" operator:

`
core/services/ardupilot_manager/main.py:101: error: Returning Any from function declared to return "_SupportsLessThan"
Found 1 error in 1 file (checked 1 source file)
`